import type { Metadata } from "next";
import "./globals.css";
import AppHeader from "./components/layout/AppHeader";
import AppFooter from "./components/layout/AppFooter";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      
      <body>
        <AppHeader />
        <main>{children}</main>
        <AppFooter />
        </body>
    </html>
  );
}
